# Resource: https://goreleaser.com/ci/actions/

name: release

on:
  push:
    tags:
      - '*'
  release:
    # Resources:
    # - https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    # - https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release
    types: [released]
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
